###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "user": "647f7cb615e8341663c8f495"
}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/647e300bf23dde3647e3003f23dde3b813fca49b813fca4c

###
PUT http://localhost:3003/api/blogs/647e3003f23dde3b813fca49
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "))))))))))"
}