###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfdXNlcm5hbWUiOiJtbHV1a2thaSIsInVzZXJuYW1lIjoibWx1dWtrYWkiLCJpZCI6IjY0N2Y3Y2I2MTVlODM0MTY2M2M4ZjQ5NSIsImlhdCI6MTY4NjM4MDIwMCwiZXhwIjoxNjg2MzgzODAwfQ.g9A8c13sU5otZjDWOAk0HW1u0uwc-bowEtgPk_pIwIg

{
    "title": "test",
    "author": "test",
    "url": "test",
    "_id": "64824c4aff3e7fee0a4ac6c5"
}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/64824c4aff3e7fee0a4ac6c5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfdXNlcm5hbWUiOiJtbHV1a2thaSIsInVzZXJuYW1lIjoibWx1dWtrYWkiLCJpZCI6IjY0N2Y3Y2I2MTVlODM0MTY2M2M4ZjQ5NSIsImlhdCI6MTY4NjM4MDIwMCwiZXhwIjoxNjg2MzgzODAwfQ.g9A8c13sU5otZjDWOAk0HW1u0uwc-bowEtgPk_pIwIg

### WRONG AUTH
DELETE http://localhost:3003/api/blogs/64824c4aff3e7fee0a4ac6c5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfdXNlcm5hbWUiOiJzdWthbG92IiwidXNlcm5hbWUiOiJzdWthbG92IiwiaWQiOiI2NDgzOGY5ZDAyM2Y4YTA0YTVlNDJiNWEiLCJpYXQiOjE2ODYzNTk2NzcsImV4cCI6MTY4NjM2MzI3N30.3CDgd2P4lbgAOTkEKC0O9RKv6ybdfS4EILGSEG3Hhho

###
PUT http://localhost:3003/api/blogs/64824c4aff3e7fee0a4ac6c5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfdXNlcm5hbWUiOiJtbHV1a2thaSIsInVzZXJuYW1lIjoibWx1dWtrYWkiLCJpZCI6IjY0N2Y3Y2I2MTVlODM0MTY2M2M4ZjQ5NSIsImlhdCI6MTY4NjM1ODUxNCwiZXhwIjoxNjg2MzYyMTE0fQ.o2gs-FUieOf9yUBffejSgcD-mbT_iQnzyc-ON6GjTD8

{
    "title": "))))",
    "author": "))))",
    "url": "))))))))))"
}

### WRONG AUTH
PUT http://localhost:3003/api/blogs/64824c4aff3e7fee0a4ac6c5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfdXNlcm5hbWUiOiJzdWthbG92IiwidXNlcm5hbWUiOiJzdWthbG92IiwiaWQiOiI2NDgzOGY5ZDAyM2Y4YTA0YTVlNDJiNWEiLCJpYXQiOjE2ODYzNTk2NzcsImV4cCI6MTY4NjM2MzI3N30.3CDgd2P4lbgAOTkEKC0O9RKv6ybdfS4EILGSEG3Hhho

{
    "title": "))))",
    "author": "))))",
    "url": "))))))))))"
}
