### no data resulting in 401
POST http://localhost:3003/api/login

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "12345678"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "mluukkai",
    "password": "wrongpassword"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "sukalov",
    "password": "00000000"
}